# Generated by Django 5.2 on 2025-05-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_uploadedimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='user',
        ),
    ]
